#!/bin/bash
# labextensions
jupyter serverextension enable --py nbgitpuller --sys-prefix
jupyter labextension install @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet
conda remove --force fsspec
pip install git+https://github.com/intake/filesystem_spec.git
